export const HTTP_STATUS_CODE = {
    OK: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    SERVER_ERROR: 500,
};

export const SUCCESS_MESSAGES = {
    // DEFAULT: "Something went Wrong...",
    USER_REGISTERED: "User Registered Seccessfully...",
    USER_LOGGED_IN: "User Logged in Successfully...",
    USER_LOGGED_OUT: "User Logged out successfully...",
    MOVIE_ADDED: "New Movie Added Successfully...",
    MOVIES_FETCHED: "Movies Fetched Successfully...",
    MOVIES_DELETED: "Movie Deleted Successfully...",
    MOVIES_UPDATED: "Movie Updated Successfuly...",
    THEATER_ADDED: "New Theater Added Successfully...",
    THEATER_FETCHED: "Theater Fetched Successfully...",
    THEATER_DELETED: "Theater Deleted Successfully...",
    THEATER_UPDATED: "Theater Updated Successfuly...",
    SCREEN_ADDED: "New Screen Added Successfully...",
    SCREEN_FETCHED: "Screen Fetched Successfully...",
    SCREEN_DELETED: "Screen Deleted Successfully...",
    SCREEN_UPDATED: "Screen Updated Successfuly...",
    SHOWTIME_ADDED: "New Showtime Added Successfully...",
    SHOWTIME_FETCHED: "Showtime Fetched Successfully...",
    SHOWTIME_DELETED: "Showtime Deleted Successfully...",
    SHOWTIME_UPDATED: "Showtime Updated Successfuly...",
    SEATS_ADDED: "New Seats Added Successfully...",
    SEATS_FETCHED: "Seats Fetched Successfully...",
    SEATS_DELETED: "Seats Deleted Successfully...",
    SEATS_UPDATED: "Seats Updated Successfuly...",
    VOUCHER_ADDED: "New Voucher Added Successfully...",
    VOUCHER_FETCHED: "New Voucher Fetched Successfully...",
    VOUCHER_UPDATED: "New Voucher Updated Successfully...",
    VOUCHER_DELETED: "New Voucher Deleted Successfully...",
    PAYMENT_UPDATED: "Payment Status Updated Successfully...",
    MOVIE_SHOW_ADDED: "User's new movie added successfully...",
    TICKET_FETCHED: "Tickets Fetched Successfully...",
    DETAILED_TICKET_FETCHED: "Detailed Ticket Fetched Successfully..."
};

export const ERROR_MESSAGES = {
    DEFAULT: "Something went Wrong...",
    USER_ALREADY_REGISTERED: "User is already Registered.",
    USER_NOT_REGISTERED: "User is not Registered.",
    UNAUTHORIZED: "Unauthorized... Login first...",
    INCORRECT_PASSWORD: "Incorrect Password...",
    PASSWORD_NOT_MATHC: "Password and Confirm Passwrod not matched...",
    HASHING_PASSWORD: "Error in Hashing Password...",
    TOKEN_MISSING: "Token is missing...",
    FILL_ALL_DETAILS: "Please fill all the details carefully.",
    MOVIE_ALREADY_EXIST: "Movie is already Existed...",
    MOVIE_NOT_FOUND: "Movie Not Found...",
    THEATER_ALREADY_EXIST: "Theater is already Existed...",
    THEATER_NOT_FOUND: "Theater Not Found...",
    SCREEN_ALREADY_EXIST: "Screen is already Existed...",
    SCREEN_NOT_FOUND: "Screen Not Found...",
    SHOWTIME_ALREADY_EXIST: "Showtime is already Existed...",
    SHOWTIME_NOT_FOUND: "Showtime Not Found...",
    SEATS_ALREADY_EXIST: "Seats is already Existed...",
    SEATS_NOT_FOUND: "Seats Not Found...",
    SCREEN_ALREADY_HAS_SEATS: "Screen have already Seats...",
    VOUCHER_ALREADY_EXIST: "Voucher is already Existed...",
    VOUCHER_NOT_FOUND: "Voucher Not Found...",
    PAYMENT_NOT_FOUND: "Payment Id Not Found...",
    INVALID_INPUT: "Invalid Input...",
    SEATS_LABEL_ALREADY_BOOKED: "Invalid or already booked seat labels...",
    MOVIE_SHOW_NOT_FOUND: "Movie Show Not Found...",
    DETAILED_TICKET_NOT_FOUND: "Detailed Ticket not Found..."
};